name: Deploy to ecs

on:
  workflow_call:
    inputs:
      role-to-assume:
        type: string
        required: false
        default: arn:aws:iam::887442827229:role/GithubActions_decidim-cfj-cdk-deploy
      image-tag:
        type: string
        required: true
      deploy-env:
        type: string
        required: false
        description: "target environment"
        default: staging

permissions:
  actions: write
  contents: read
  id-token: write

jobs:
  deploy:
    name: aws cdk
    runs-on: ubuntu-latest
    timeout-minutes: 1800
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ inputs.role-to-assume }}
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Check if ECR Image exists with tag
        if: contains(github.ref, 'tags/v')
        env:
          IMAGE_TAG: ${{ inputs.image-tag }}
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPO_NAME }}
        run: |
          EXIT_CODE=0
          aws ecr describe-images --repository-name=$ECR_REPOSITORY --image-ids=imageTag=$IMAGE_TAG 2> /dev/null || EXIT_CODE=$?

          if [[ $EXIT_CODE != 0 ]]; then
              echo "${IMAGE_TAG} image tag not found"
              exit 1
          fi

      - name: Checkout decidim-cfj cdk
        uses: actions/checkout@v3
        with:
          repository: codeforjapan/decidim-cfj-cdk
          path: decidim-cfj-cdk

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '22'

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm install
        working-directory: decidim-cfj-cdk

      - name: Install dependencies
        run: npm install -g aws-cdk
        working-directory: decidim-cfj-cdk

      - name: cdk deploy
        run: cdk -c stage=$DEPLOY_ENV -c tag=$IMAGE_TAG deploy --all --require-approval never
        working-directory: decidim-cfj-cdk
        env:
          AWS_DEFAULT_REGION: 'ap-northeast-1'
          DEPLOY_ENV: ${{ inputs.deploy-env }}
          IMAGE_TAG: ${{ inputs.deploy-env }}-${{ inputs.image-tag }}
